version: '3.8'

services:
  kong:
    image: kong:3.4
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
    volumes:
      - ../kong.yml:/etc/kong/kong.yml
    ports:
      - "8000:8000"  # Kong proxy port
      - "8001:8001"  # Admin API (optional)
    depends_on:
      - httpbin

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "8080:8080"
